### ISSUE TITLE
Vite JS Production Build

### ISSUE THREAD

**Issue by eliyammine** [cds-snc/gcds-components#174]
Hi,

I have been developing in dev mode in Vite with no issues with the library. When attempting to build-deploy I am getting these errors:

![image](https://github.com/cds-snc/gcds-components/assets/6644807/39ed8131-ea43-4f69-97fb-a656cdbc335c)

I have done some research and these are some relevant issues I found:
https://github.com/ionic-team/stencil/issues/2827
https://github.com/vitejs/vite-plugin-react/issues/89

There appears to a build-flag in Stencil that should make this error go away:
https://stenciljs.com/docs/config-extras#enableimportinjection

Eli

**Comment by eliyammine** [comment]
Spoke too soon on this one. I found a workaround via the config again.

1. npm i vite-plugin-dynamic-import -D
2. In vite.config.ts add the following:
```
import dynamicImport from 'vite-plugin-dynamic-import';

plugins: [
	dynamicImport({
		filter(id) {
			if (id.includes('/node_modules/@cdssnc')) {
				return true;
			}
		},
	}),
],
```

Will just leave this here incase anyone else experiences it

**Comment by verena-ifx** [comment]
is there any update on this?
