### ISSUE TITLE
Local installation issues.

### ISSUE THREAD

**Issue by paper-19** [cds-snc/gcds-components#192]
Couple of issues I ran into while building according to the local installation part of readme.md.

- Missing workspaces in root `package.json`, couple of steps in local installation part of readme.md don't function as result.
- `gcds-components\packages\web\package.json` broken `postbuild` script on Windows, suggest using `fs.copyFileSync()` script.

**Comment by ethanWallace** [comment]
We have updated the readme to better reflect the project setup in our `v0.12.0` release. Thanks!
