### ISSUE TITLE
Missing icon in the navigation menu

### ISSUE THREAD

**Issue by Nassehk** [cds-snc/gcds-components#345]
Hi GCDS team,
I noticed missing icon next to navigation links in the horizontal menu. Am I doing something wrong? 
This is what it looks like:
![image](https://github.com/cds-snc/gcds-components/assets/22254869/42a1b573-404d-495d-a475-54b2920a9fd2)

Here is my code:
```
<!-- GC Design System -->
<link rel="stylesheet" href="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@latest/dist/gcds/gcds.css">
<script type="module" src="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@latest/dist/gcds/gcds.esm.js"></script>
<script nomodule src="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@latest/dist/gcds/gcds.js"></script>
<gcds-header>
  <gcds-top-nav
  label="Top navigation"
  alignment="right"
  slot = 'menu'
>
  <gcds-nav-link href="/" slot="home">Wellcome to SLIM</gcds-nav-link> 
    <gcds-nav-group  open-trigger="Requisitions" menu-label="Requisitions">
    <gcds-nav-link href="#">create</gcds-nav-link>
    <gcds-nav-link href="#">search</gcds-nav-link>
  </gcds-nav-group>
  <gcds-nav-group  open-trigger="Data" menu-label="Data">
    <gcds-nav-link href="#">create</gcds-nav-link>
    <gcds-nav-link href="#">search</gcds-nav-link>
  </gcds-nav-group>
  <gcds-nav-link href="#" >logout</gcds-nav-link>
</gcds-top-nav>
</gcds-header>
```

**Comment by melaniebmn** [comment]
Hi @Nassehk,

Can you try adding the following link to the head of your project in order to see if that fixes the icons for you?
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous">
```

Please let us know if you still have issues after that.

**Comment by Nassehk** [comment]
Awesome! It worked. I got my code from the example on the horizontal nav menu. If possible it would help if the link you mentioned can be added to the code example.

**Comment by melaniebmn** [comment]
Awesome, happy to hear it worked! We updated our installation instructions to make it clearer that the Font Awesome link needs to be added in order for icons to work. We are also currently working on removing that dependency so that you don't have to worry about this at all anymore.

**Comment by Nassehk** [comment]
Wonderful!

**Comment by tim-meredith-acoa** [comment]
I believe this is still an issue in the React instructions. I was thinking it might pull in FontAwesome over NPM, but it doesn't seem to, I still have missing icons, so the instruction to add the FontAwesome CDN should probably be added to the React instructions as well.
