### ISSUE TITLE
Missing type declarations in gcds-components-react 

### ISSUE THREAD

**Issue by mghughes** [cds-snc/gcds-components#466]
I'm getting the following error when using `gcds-components-react` with typescript in v0.19.0 and later:

`TS7016: Could not find a declaration file for module '@cdssnc/gcds-components-react'`

Let me know if I'm missing something, but I believe [this change](https://github.com/cds-snc/gcds-components/commit/424b138d6ebf8e3df77b2e265ff386bf1e39d7cf#diff-1f344ac391eeecc21ec0f01fb07430a47f4b80d20485c125447d54c33c4bbfc4L23) is the cause. When I install `gcds-components-react`, the file is still at `dist/index.d.ts` so `package.json` seems to be pointing to the wrong place now, and changing that back locally has fixed the issue for me.

**Comment by daine** [comment]
@mghughes Thank you for reporting this bug, we have a fix and it should be out on our next release. In the meantime, locally updating the path like you did also works to resolve the issue. We apologize for the inconvenience.

**Comment by mghughes** [comment]
Thanks @daine!
