### ISSUE TITLE
Handling events in Angular components

### ISSUE THREAD

**Issue by fgoulet** [cds-snc/gcds-components#473]
I'm just starting to experiment with the gcds-components in an Angular application.

It seems that the Angular components do not contain any "@Output()" properties.

For example, the gcds-select web component has a gcdsChange event but the angular "wrapper" does not expose that event with an "@Output()".

Do I miss something or is this something planned for a future release ?

**Comment by ethanWallace** [comment]
Thank you for flagging this with us.

We generate our angular wrappers using a package called `@stencil/angular-output-target`. We will take a look into why it is not using `@output`.

**Comment by ethanWallace** [comment]
Hey @fgoulet, we have just recently released version `0.22.0` of the `@cdssnc/gcds-components-angular` package that should now feature `outputs` on the angular components. We haven't been able to look into the link issue yet but let me know if your outputs issue has been resolved. 

Thank you

**Comment by fgoulet** [comment]
Thank you @ethanWallace , I will give it a try.

**Comment by ethanWallace** [comment]
@fgoulet Sorry for the delay. The duplicate events should now be solved in `v0.22.2`.
