### ISSUE TITLE
Design: Add visited state to Link

### ISSUE THREAD

**Issue by adorayi** [cds-snc/gcds-components#571]
**Summary:** Update design of the link component to include a visited state, to align with Canada.ca.
Design on component branch and push to main Figma file when approved.

## Acceptance Criteria

- [x] Link visited state has colour: #7532B8
- [x] Link has value: **Visited** within property: **State**

## Definition of done
- [x] EN component is ready for merge
- [x] FR component is ready for merge
- [x] Update #572 (dev ticket) with link to design  
- [x] Review and update requirements doc with developer (if applicable)

## Deliverables

- [x] [EN component](https://www.figma.com/design/csxWG91cmWVtuRCrAs5C24/Visited-Link?node-id=9557-58&t=1sbmbB0F90Mt0I2B-4)
- [x] [FR component](https://www.figma.com/design/xqEsin81HJNCUBJvc1J0lr/Les-variables?node-id=118-11049&t=1sbmbB0F90Mt0I2B-4)

## Dev impact
**Yes** - Add visited link state to code #572

**Comment by adorayi** [comment]
Would the visited state apply to all link component instances or not.

**Comment by realdylanzheng** [comment]
@adorayi 'push to main Figma when approved' - who's to approve? 
How do we take into consider what has transpired with the incidents?

**Comment by adorayi** [comment]
@realdylanzheng as long as other designers have reviewed and it's been shown to devs for feedback as well it can be pushed.

**Comment by melaniebmn** [comment]
Note: after talking to @realdylanzheng we decided to change the colour from #7834BC to #7532B8 to keep a minimum 7:1 colour contrast ratio that we ensure for all other 700 and above colour tokens.

**Comment by melaniebmn** [comment]
@realdylanzheng can we add the new purple colour to the "Styles" page in Figma as well to make sure we keep track of all of our colours there as well?
