### ISSUE TITLE
Dev: update link component to add visited state

### ISSUE THREAD

**Issue by adorayi** [cds-snc/gcds-components#572]
**Summary:** Update the code of the link component to include a visited state, to align with Canada.ca.

[Figma | Link component](https://www.figma.com/design/csxWG91cmWVtuRCrAs5C24/Visited-Link?node-id=9557-58&t=W7NDo7mDqMl2fRbc-4)

- [x] Sync with Design
- [x] Update Requirements documentation
- [x] Review of requirements doc
- [x] Add new global token for visited link
- [x] Update link styling in utility framework
- [x] Update storybook
- [x] Update dev guidance if needed
- [x] Develop the component according to the requirements doc and design specs
- [x] Sync dev properties with Figma properties (design + dev)
- [x] Final sync with Design
- [x] Code review
- [x] Push to prod

## Acceptance Criteria

- [x] The link component code includes a visited state.
- [x] Storybook and code editor reflect new state
- [x] New global token has been added
- [x]  New visited link styling has been added to the utility framework
- [x] Release notes are included

**Comment by melaniebmn** [comment]
The new global token was added in this [PR](https://github.com/cds-snc/gcds-tokens/pull/298).

**Comment by melaniebmn** [comment]
The visited state was added to the link component in this [PR](https://github.com/cds-snc/gcds-components/pull/602).

**Comment by melaniebmn** [comment]
The visited link styling was added to the utility framework in this [PR](https://github.com/cds-snc/gcds-utility/pull/169).
