### ISSUE TITLE
Links do not render underline in Safari

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/gcds-components#576]
In the Safari browser, elements using the link style do not render the underline reducing the perceivability of those strings of text to be interacted with.

![Screenshot 2024-07-02 at 12 23 03 PM](https://github.com/cds-snc/gcds-components/assets/10466431/da383830-f39b-4374-abaa-90820511b61f)

**Comment by adorayi** [comment]
Requires investigation.
