### ISSUE TITLE
Support for angular version 18 and 19

### ISSUE THREAD

**Issue by brockhigg10** [cds-snc/gcds-components#628]
### Prerequisites | Prérequis

- [X] I have read the [Contributing Guidelines](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md). | J’ai lu les [Lignes directrices sur les contributions](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md). | J’accepte de me conformer au [Code de conduite](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/cds-snc/gcds-components/issues) that already report this problem, without success. | J’ai vérifié parmi [les tickets (issues) existants](https://github.com/cds-snc/gcds-components/issues) que ce sujet n’avait pas déjà été soumis.

### GC Design System Components Package and Version | Paquet et version des composants de Système de design GC

gcds-components-angular@x.x.x

### Current Behavior | Comportement observé

"I worked on creating a form in Angular using GCDS. Turns out it worked better than I anticipated: I was able to bind the values from my model to the GCDS components!

Here is the result: [https://stackblitz.com/github/AlexisLeblancDFO/gcds-angular18-form?file=README.md](https://stackblitz.com/github/AlexisLeblancDFO/gcds-angular18-form?file=README.md)

As you will notice when opening the link: there are multiple error messages that occur when installing GCDS.

The issue is that the latest version of GCDS is only compatible with Angular 16 and less (we are at version 18 now).

It may become an issue as the project gets bigger. At the moment, it’s the only issue I have with GCDS."

### Expected Behavior | Comportement attendu

Would it be possible to release an version of GCDS that supports Angular 18?

### Steps to Reproduce | Étapes pour reproduire le bogue

[https://stackblitz.com/github/AlexisLeblancDFO/gcds-angular18-form?file=README.md](https://stackblitz.com/github/AlexisLeblancDFO/gcds-angular18-form?file=README.md)

**Comment by ethanWallace** [comment]
@daine I have tested setting the dependencies to Angular@18.2.13 and Typescript@5.5.0 to see if the same strange build errors occur.

The react build will still fail with the same error and the react ssr now fails too with an error similar to the react error. The angular package did load fine though when using it in a test app.

**Comment by daine** [comment]
This has been done and released with version 0.30.0 
https://github.com/cds-snc/gcds-components/blob/main/CHANGELOG.md#0300
