### ISSUE TITLE
feat: Add a new prop to <gcds-details> that would optimize for print

### ISSUE THREAD

**Issue by CraigClark** [cds-snc/gcds-components#700]
### Prerequisites | Prérequis

- [X] I've read the [Contributing Guidelines](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md). | J’ai lu les [Lignes directrices sur les contributions](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md). | J’accepte de me conformer au [Code de conduite](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md).
- [X] I've searched for [existing issues](https://github.com/cds-snc/gcds-components/issues) that already report this problem, without success. | J’ai vérifié parmi les [tickets (issues) existants](https://github.com/cds-snc/gcds-components/issues) que ce sujet n’avait pas déjà été soumis.

### Describe the feature request. | Décrivez la fonctionnalité demandée

Add a `print-expanded` prop to the `<gcds-details>` component for optimized print output.

This feature would introduce a new prop to the `<gcds-details>` component, ensuring the content within is automatically expanded when the page is printed. Additionally, screen-specific styles would be removed, providing a clean and readable print layout.

**Proposed Print Appearance**:  
When printed, the `<gcds-details>` content would appear expanded for better accessibility and usability.  
![details-print](https://github.com/user-attachments/assets/64e4c8ff-da81-4556-8bf4-ad4f07070646)

**Existing Appearance (Screen)**:  
For comparison, here is the current screen appearance of the `<gcds-details>` component.  
![details-screen](https://github.com/user-attachments/assets/fbdfa965-29a5-45dd-90ac-21460853ce46)

This enhancement would improve the user experience by making printed content more comprehensive and removing unnecessary styling elements.

### Describe the use case. | Décrivez les cas d’utilisation

**Use Case**: 

In some scenarios, content is collapsed to reduce visual clutter on the screen or to make sub-headings more scannable. However, when printing the page, it is often desirable for this content to be fully exposed to ensure all information is accessible and readable in a print format.

In other cases, where auxiliary information is collapsed (e.g., in a data dictionary with dozens of items), keeping the content collapsed during printing might be more appropriate. For example, expanding all items could overwhelm the printed output.

Adding a `print-expanded` prop would empower content experts to decide whether specific collapsed content should be expanded or remain collapsed when printed, ensuring flexibility for various use cases.
 

### Describe the preferred solution. | Décrivez la solution souhaitée

1. Add a new prop to the `<gcds-details>` component, such as `print-expanded`.  

2. Update the component's stylesheet to include a print-specific media query (`@media print {…}`) that would:  
   - Automatically expand and display the content within the `details__panel` when printed.  
   - Remove screen-specific styles, such as the caret and thick left margin, that are unnecessary or distracting in print.  
   - Enhance the `details summary` by adding increased font weight for better visibility and clarity in print.  

### Describe all alternatives. | Décrivez toutes les solutions possibles

**Alternatives**:  

### 1. Do Nothing: Rely on the user to expand/collapse elements manually  
- **Advantage**:  
  - Users have direct control over what content is expanded and printed.  

- **Disadvantage**:  
  - Poor user experience if there are many `<gcds-details>` elements or scrolling is required between them.  
  - Users might not realize they need to expand elements for printing, leading to wasted effort and resources from printing multiple times.  
  - Negative UX and environmental impacts due to unnecessary reprints.  

### 2. Per Project: Create an _Expand/Collapse All_ Button for `<gcds-details>`  

I'm not sure this would work, I haven't tried it, it's based on the assumption that we can control props with JavaScript.

- **Advantage**:  
  - Provides users with a quick and efficient way to expand or collapse all `<gcds-details>` elements, improving readability both on screen and in print.  

- **Disadvantage**:  
  - Assumes developers have the knowledge and access to create a JavaScript-based button to control the `<gcds-details>` elements.  
  - Users may still not realize they need to expand everything before printing, leading to potential reprints.  
  - Limited applicability, as this solution works best when all `<gcds-details>` elements are siblings.  

Both alternatives have significant limitations in terms of usability and consistency,

### Add other relevant resources. | Ajoutez toute autre ressource utile

- [A similar feature has just been added by the W3C to the HTML spec](https://github.com/w3c/csswg-drafts/issues/2084) for `<details>` elements:  
  This feature is currently experimental and not widely supported in browsers.

- **Applicability to GCDS Details Component**:  
  This limitation does not affect the GCDS details component since it renders custom HTML instead of a native `<details>` element.

**Comment by daine** [comment]
@CraigClark thanks for submitting an issue, we will look into this as a team on how we can support adding a feature to support expanded text on print view on the details component.

Please react with a 👍 on the issue if this is something that affects you, it helps us with prioritization. If you have any use-cases, screenshots, etc to share, please don't hesitate to [reach out to us](https://design-system.alpha.canada.ca/en/contact/)

**Comment by CraigClark** [comment]
@daine 
Thank you for the reply.
Here are some screenshot of what we are trying to do.

---

For reference, this is what the screen looks like by default

<img width="942" alt="gcds-details-screen" src="https://github.com/user-attachments/assets/0a8ed6e8-8952-4538-8e80-cb172e935f90" />

---

When the page is printed, the `<details>` remains collapsed.

<img width="638" alt="gcds-details-print-details-closed" src="https://github.com/user-attachments/assets/c0dc9d2a-de86-4539-8554-e257147f9251" />

---

Expanding all `<details>` makes a more visually cohesive printout. However, as noted in my request, requiring users to manually expand all details before printing may presents usability challenges. 

<img width="628" alt="gcds-details-print-details-open" src="https://github.com/user-attachments/assets/8cf95f00-ca99-4cf0-9f04-7f590a991f82" />

---

While printing `<details>` expanded would make the content readily available, it would be best if the button was styled in a way more suitable for print

<img width="553" alt="gcds-details-print-details-print-optimized" src="https://github.com/user-attachments/assets/93cd1e15-a591-450f-8c70-41a4515e690d" />

---

I'm imagining a situation where:

1. content creator adds prop `print-expanded` to `<gcds-details>`
2. on seeing the prop, the JS adds a class `print-expanded`
3. `print-expanded` is inside a print media query `(@media print {…})`

you would have something like



```css
@media print {
  .gcds-details .details__summary {
    /* remove button styles and replace with something that looks like a heading */
  }
  .gcds-details .details__panel.print-expanded {
    display: block;
  }
}

**Comment by melaniebmn** [comment]
Hello @CraigClark ,

Thank you so much for reaching out and for providing such great examples! They've really helped us understand the context better.

After reviewing your suggestion, we decided to expand all detail components by default for print rather than add a prop. The reason is that, as implementors and content creators, we don't always have enough insight into which specific information will be most important to users in different contexts. Since we can't fully predict which details should be expanded or collapsed for each user, we need to conduct more research to determine if a new `print-expanded` prop would be a better solution. 

We have modified the styling of the details component to look like this for print:

![Screenshot 2024-12-17 at 4 23 12 PM](https://github.com/user-attachments/assets/f9d00bb3-4796-4de5-9a6f-9f50b63987ce)

The updated print design for the details component is now available in the [latest version](https://github.com/cds-snc/gcds-components/blob/main/CHANGELOG.md) of our component package (v0.30.0).

Does this approach help resolve the issue you encountered, or would you like to explore other alternatives? We'd love to hear your thoughts!

Thank you again for creating this feature request and providing a detailed description with examples!

**Comment by CraigClark** [comment]
@melaniebmn 
This resolves it. Thank you!
